### ISSUE TITLE
PY Loops link points to FUNCTIONS video

### ISSUE THREAD

**Issue by jhealy** [microsoft/EveryoneCanCode-US#68]
LOOPS actually points to FUNCTIONS in doc -  https://github.com/microsoft/EveryoneCanCode-US/blob/main/Track_1_ToDo_App/Sprint-01%20-%20Basic%20Application/Feature%201%20-%20Manage%20Todo%20List/User%20Story%201%20-%20Add%20Item%20to%20List.MD

**Comment by johndehavilland** [comment]
fixed

**Comment by johndehavilland** [comment]
fixed link
